camps-index:
  image: gcr.io/midbarrn/midburn-camps-index-cd:14590fb7494ebab5a98784165150ad7a99b966b1
chatops:
  image: gcr.io/midbarrn/midburn-chatops-cd:87918a8e169c114104ec19061dac2d8c2cd51432
dreams:
  image: gcr.io/midbarrn/midburn-dreams-cd:ceb3bc44416047493316f7edc198dd1cd7de57a3
global:
  opsImage: gcr.io/uumpa123/midburn-k8s:24fb296508dcf05202b9bbb3ffb7c9bdd47a7128
spark:
  image: gcr.io/midbarrn/midburn-spark-cd:26ba6c6936fa926dfafa4acc79d0c1a022510f48
volunteers:
  image: gcr.io/midbarrn/midburn-volunteers-cd:2deb9d33df8a6cdea9da929a62e594490839f8df
