global:
  defaultNodePool: default-pool
  k8sOpsSecretName: ops
  k8sOpsImage: gcr.io/uumpa123/midburn-k8s
  environmentName: staging
  opsRepoSlug: Midburn/midburn-k8s
  opsRepoBranch: master
  googleProjectId: midbarrn
  projectName: midburn
  enableRootChart: true
  backupsBucketName: midburn-k8s-backups
  # this is the same for all environments
  # gcloud compute instances describe midburn-k8s-persistent-storage-vm --zone=us-central1-a --format='value(networkInterfaces[0].networkIP)'
  persistentStorageIP: 10.128.0.7

traefik:
  enabled: true
  acmeDomains: |
    [[acme.domains]]
      main = "spark.staging.midburn.org"
    [[acme.domains]]
      main = "staging.midburn.org"
    [[acme.domains]]
      main = "volunteers.staging.midburn.org"
    [[acme.domains]]
      main = "profiles.staging.midburn.org"
  acmeEmail: ori@uumpa.com
  dnsProvider: route53
  AWS_ACCESS_KEY_ID: AKIAIJUE2QVTBJAN7INQ
  AWS_REGION: "eu-west-1"
  sparkHostsRule: "Host: spark.staging.midburn.org;"
  volunteersHostsRule: "Host: volunteers.staging.midburn.org;"
  # gcloud compute addresses create midburn-staging-traefik --region=us-central1
  # gcloud compute addresses describe midburn-staging-traefik --region=us-central1 | grep ^address:
  loadBalancerIP: "35.225.81.109"
  enableVolunteers: true
#  nodeHostName: gke-midbarrn-default-pool-ed511f2f-p08j
  backupJob: true
  enableLoadBalancer: true
  profilesHostsRule: "Host: profiles.staging.midburn.org;"
#  SSLcheckMainDomain: staging.midburn.org
#  SSLcheckSparkDomain: spark.staging.midburn.org
#  SSLcheckProfilesDomain: profiles.staging.midburn.org
#  SSLcheckVolunteersDomain: volunteers.staging.midburn.org

spark:
#  nodeEnv: production
  enableSlackNotification: true
  serverUrl: https://spark.staging.midburn.org/

  # DB
  rootSecretName: sparkdb-root
  appSecretName: sparkdb-app
  dbBackupJob: true
  # persistent storage was setup using environments/staging/persistent_storage_migration.sh
  persistentStorageName: sparkdb


  # Mail - using Ori's Mailjet account
  disableMailtrap: "true"
  secureMailserverSecretName: spark-mail
  mailserverFrom: support@spark.staging.midburn.org
  mailserverHost: in-v3.mailjet.com
  mailserverPort: 2525

  # Drupal
  drupalSecretName: spark-drupal
  drupalProfileApiURL: https://profile.midburn.org
  drupalProfileApiUser: spark@midburn.org
  DRUPAL_TICKET_SYNC_EVERY_X_MINUTES: "2"

  # Volunteers
  volunteersBaseUrl: https://volunteers.staging.midburn.org

nginx:
  htpasswdSecretName: nginx-htpasswd

volunteers:
  ENVIRONMENT: staging
  SPARK_HOST: https://spark.staging.midburn.org
  dbImportJob:
    IMPORT_URL: gs://midburn-k8s-backups/volunteersdb-production-mongodump-2018-01-06-12-21.tar.gz
  dbBackupJob: true

profiles:
  dbImage: gcr.io/midbarrn/midburn-profiles-drupal-db-latest
  image: gcr.io/midbarrn/midburn-profiles-drupal-latest
  enabled: true
  # dbImportUrl: gs://midburn-k8s-backups/profiles-db-production-dump-2018-01-16-11-30.sql
  # NO trailing slash!
  drupalBaseUrl: https://profiles.staging.midburn.org

bi:
  enabled: false

dreams:
  enabled: true
  APP_URL: https://dreams.staging.midburn.org/
