camps-index:
  image: gcr.io/midbarrn/midburn-camps-index-cd:14590fb7494ebab5a98784165150ad7a99b966b1
chatops:
  image: gcr.io/midbarrn/midburn-chatops-cd:87918a8e169c114104ec19061dac2d8c2cd51432
dreams:
  image: gcr.io/midbarrn/midburn-dreams-cd:a9d1f554968c4209bc8187966b46ca067bb98747
global:
  opsImage: gcr.io/uumpa123/midburn-k8s:24fb296508dcf05202b9bbb3ffb7c9bdd47a7128
spark:
  image: gcr.io/midbarrn/midburn-spark-cd:5ed40f011aa66b16741606f9ef4559a7093f0f23
volunteers:
  image: gcr.io/midbarrn/midburn-volunteers-cd:8b32106afeab10dc0ed82f1ca9fbe7585199e715
