global:
  defaultNodePool: default-pool
  k8sOpsSecretName: ops
  k8sOpsImage: gcr.io/uumpa123/midburn-k8s
  environmentName: staging
  opsRepoSlug: Midburn/midburn-k8s
  opsRepoBranch: master
  googleProjectId: midbarrn
  projectName: midburn
  enableRootChart: true

traefik:
  enabled: true
  acmeDomains: |
    [[acme.domains]]
      main = "spark.staging.midburn.org"
    [[acme.domains]]
      main = "staging.midburn.org"
    [[acme.domains]]
      main = "volunteers.staging.midburn.org"
  acmeEmail: ori@uumpa.com
  sparkHostsRule: "Host: spark.staging.midburn.org;"
  volunteersHostsRule: "Host: volunteers.staging.midburn.org;"
  # gcloud compute addresses create midburn-staging-traefik --region=us-central1
  # gcloud compute addresses describe midburn-staging-traefik --region=us-central1 | grep ^address:
  loadBalancerIP: "35.225.81.109"
  enableVolunteers: true
#  nodeHostName: gke-midbarrn-default-pool-ed511f2f-p08j
  backupJob: true

spark:
#  nodeEnv: production
  enableSlackNotification: true
  serverUrl: https://spark.staging.midburn.org/

  # DB
  rootSecretName: sparkdb-root
  appSecretName: sparkdb-app

  # import database from spark production
  dbImportJob:
    IMPORT_URL: gs://midburn-k8s-backups/sparkdb-production-dump-2018-01-06-12-16.sql
  dbBackupJob: true

  # Mail - using Ori's Mailjet account
  disableMailtrap: "true"
  secureMailserverSecretName: spark-mail
  mailserverFrom: support@spark.staging.midburn.org
  mailserverHost: in-v3.mailjet.com
  mailserverPort: 2525

  # Drupal
  drupalSecretName: spark-drupal
  drupalProfileApiURL: https://profile.midburn.org
  drupalProfileApiUser: spark@midburn.org
  DRUPAL_TICKET_SYNC_EVERY_X_MINUTES: "2"

  # Volunteers
  volunteersBaseUrl: https://volunteers.staging.midburn.org

nginx:
  htpasswdSecretName: nginx-htpasswd

volunteers:
  ENVIRONMENT: staging
  SPARK_HOST: https://spark.staging.midburn.org
  dbImportJob:
    IMPORT_URL: gs://midburn-k8s-backups/volunteersdb-production-mongodump-2018-01-06-12-21.tar.gz
  dbBackupJob: true
