{{ if .Values.traefik.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-traefik
data:
  traefik.toml: |
    # https://docs.traefik.io/configuration/commons/

    {{ if .Values.global.debug }}
    debug = true
    {{ end }}

    defaultEntryPoints = ["http", "https"]
    
    [entryPoints]
        [entryPoints.http]
          address = ":80"
            [entryPoints.http.redirect]
              entryPoint = "https"
        
        [entryPoints.https]
          address = ":443"
            [entryPoints.https.tls]

    {{ if .Values.traefik.acmeEmail }}
    # let's encrypt automatic ssl certificate issue and renewal
    [acme]
      email = {{ .Values.traefik.acmeEmail | quote }}
      storage = "/traefic-acme/acme.json"
      entryPoint = "https"
{{ .Values.traefik.acmeDomains | indent 6 }}
    {{ end }}

    [file]
    
    [backends]
      {{ if .Values.nginx.enabled }}
      [backends.nginx]
        [backends.nginx.servers.server1]
          url = "http://nginx:80"
      {{ end }}

      {{ if .Values.spark.enabled }}
      [backends.spark]
        [backends.spark.servers.server1]
          url = "http://spark:3000"
      {{ end }}

    [frontends]
      {{ if .Values.nginx.enabled }}
      [frontends.default]
        backend="nginx"
        passHostHeader = true
      {{ end }}

      {{ if .Values.spark.enabled }}
      [frontends.spark]
        backend="spark"
        passHostHeader = true
          [frontends.spark.routes.route1]
            rule = "{{ .Values.traefik.sparkHostsRule }}"
      {{ end }}

{{ end }}
