camps-index:
  image: gcr.io/midbarrn/midburn-camps-index-tag:v1.3.1
chatops:
  image: gcr.io/midbarrn/midburn-chatops-cd:11bf6c93148b1b259ab0251e4352116eefdde56d
dreams:
  image: gcr.io/midbarrn/midburn-dreams-tag:v3.0.3
global:
  opsImage: gcr.io/uumpa123/midburn-k8s:24fb296508dcf05202b9bbb3ffb7c9bdd47a7128
spark:
  image: gcr.io/midbarrn/midburn-spark-tag:v3.2.8
volunteers:
  image: gcr.io/midbarrn/midburn-volunteers-cd:6a05860943d6b462ee5cede1e1683450cf44e918
